global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "musicstream-api"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["api:3000"]

  - job_name: "invidious"
    metrics_path: /api/v1/stats
    static_configs:
      - targets: ["invidious:3001"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
